---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
    ioapic: 'on'

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    attributes:
      java:
        jdk_version: 7
  - name: debian-7.2.0
    run_list:
      - recipe[apt]
    attributes:
      java:
        jdk_version: 6
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
    attributes:
      java:
        jdk_version: 7
  - name: ubuntu-13.10
    run_list:
      - recipe[apt]
    attributes:
      java:
        jdk_version: 7
  - name: fedora-18
    attributes:
      java:
        jdk_version: 7

suites:
  - name: init-style-upstart
    run_list:
      - recipe[java::default]
      - recipe[kafka]
    excludes:
      - centos-6.5
      - debian-7.2.0
      - fedora-18
    attributes:
      kafka:
        init_style: 'upstart'
        zookeeper:
          connect: ['localhost:2181']
          connection_timeout_ms: 15_000
  - name: init-style-sysv
    run_list:
      - recipe[java::default]
      - recipe[kafka]
    attributes:
      kafka:
        zookeeper:
          connect: ['localhost:2181']
          connection_timeout_ms: 15_000
  - name: binary
    run_list:
      - recipe[java::default]
      - recipe[kafka]
    attributes:
      kafka:
        install_method: 'binary'
  - name: source
    run_list:
      - recipe[java::default]
      - recipe[kafka]
    attributes:
      kafka:
        checksum: '123c72a6d7562db836c71362ae9c6bc21e9549cf20c97cccf9acef0a83118f74'
        md5_checksum: '81f1d7067c9848ecacebb16561b992d4'
        install_method: 'source'
  - name: zookeeper
    run_list:
      - recipe[java::default]
      - recipe[kafka::zookeeper]
    attributes:
      kafka:
        zookeeper:
          connect: ['localhost:2181']
          connection_timeout_ms: 15_000
